name: GitHub Actions Demo
on: [push] 
jobs:
  build:
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: install modules
        run: npm install 
      - name: build project
        run: npm run build
  test:
    runs-on: macos-latest 
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: install modules
        run: npm install 
      - name: test project
        run: npm run test