name: GitHub Actions Demo
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  build:
    runs-on: macos-latest 
    steps:
      - name: get rep
        uses: actions/checkout@v3
      - name: Cache Primes
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - name: install modules
        run: npm install 
      - name: build project
        run: npm run build