name: GitHub Actions Demo
on: 
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: get rep
        uses: actions/checkout@v3
      - name: Cache Primes
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - name: install modules
        run: npm install 
      - name: build project
        run: npm run build
      - name: Upload Wrifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-fules
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build project
        uses: action/download-artifact@v3
        with: 
          name: dist-files